//
//  NearestStationsService.swift
//  Schedulo
//
//  Created by Viktor Zavhorodnii on 03/06/2025.
//

import OpenAPIRuntime
import OpenAPIURLSession

typealias NearestStations = Components.Schemas.Stations

protocol NearestStationsServiceProtocol {
    func getNearestStations(lat: Double, lng: Double, distance: Int) async throws -> NearestStations
}

/// Service provides wrapper over the autogenerated OpenAPI client for the "getNearestStations" method
final class NearestStationsService: NearestStationsServiceProtocol {
    private let client: Client
    private let apikey: String
    
    init(client: Client, apikey: String) {
        self.client = client
        self.apikey = apikey
    }
    
    /// Retrieves a list of stations located within given radius. Max 50
    /// - Parameters:
    ///   - lat: latitude
    ///   - lng: longitude
    ///   - distance: distance from a given position
    /// - Returns: a list of station located within the radius
    func getNearestStations(lat: Double, lng: Double, distance: Int) async throws -> NearestStations {
        let response = try await client.getNearestStations(query: .init(
            apikey: apikey,
            lat: lat,
            lng: lng,
            distance: distance
        ))
        
        return try response.ok.body.json
    }
}

/// Func for test API call "getNearestStations" method
func testFetchStations() {
    Task {
        do {
            let client = Client(
                serverURL: try Servers.Server1.url(),
                transport: URLSessionTransport()
            )
            
            let service = NearestStationsService(
                client: client,
                apikey: "3c35e80c-ee35-4151-9e13-348cf777ab10"
            )
            
            print("Fetching stations...")
            let stations = try await service.getNearestStations(
                lat: 51.107883,
                lng: 17.038538,
                distance: 50
            )
            
            print("Successfully fetched stations: \(stations)")
        } catch {
            print("Error fetching stations: \(error)")
        }
    }
}
