//
//  RoutesBetweenStationsService.swift
//  Schedulo
//
//  Created by Viktor Zavhorodnii on 04/06/2025.
//

import OpenAPIRuntime
import OpenAPIURLSession

typealias RoutesBetweenStations = Components.Schemas.Segments

protocol RoutesBetweenStationsServiceProtocol {
    func getRoutesBetweenStations(from: String, to: String) async throws -> RoutesBetweenStations
}

/// Service provides wrapper over the autogenerated OpenAPI client for the "getScheduleBetweenStations" method
final class RoutesBetweenStationsService: RoutesBetweenStationsServiceProtocol {
    private let client: Client
    private let apikey: String
    
    init(client: Client, apikey: String) {
        self.client = client
        self.apikey = apikey
    }
    
    ///  Perform request for list of trips between specified stations
    /// - Parameters:
    ///   - from: departure station
    ///   - to: arrival station
    /// - Returns: a list of trips from the specified departure station to the specified arrival station, along with details for each trip.
    func getRoutesBetweenStations(from: String, to: String) async throws -> RoutesBetweenStations {
        let response = try await client.getScheduleBetweenStations(query: .init(
            apikey: apikey,
            from: from,
            to: to,
        ))
        
        return try response.ok.body.json
    }
}

/// Func for test call API request "getScheduleBetweenStations" method
func testFetchRoutesBetweenStations() {
    Task {
        do {
            let client = Client(
                serverURL: try Servers.Server1.url(),
                transport: URLSessionTransport()
            )
            
            let service = RoutesBetweenStationsService(
                client: client,
                apikey: appKeys.yandexRaspAPIKey.rawValue
            )
            
            print("Fetching routes between stations...")
            let response = try await service.getRoutesBetweenStations(
                from: "s2000001",
                to: "s9605027",
            )
            print("Got response:", response)
        } catch {
            print("Error fetching routes between stations:", error)
        }
    }
}
