//
//  ListOfStationsService.swift
//  Schedulo
//
//  Created by Viktor Zavhorodnii on 08/06/2025.
//

import OpenAPIRuntime
import OpenAPIURLSession

typealias ThreadOfStations = Components.Schemas.ThreadStationsResponse

protocol ThreadOfStationsServiceProtocol {
    func getThreadOfStations(by: String) async throws -> ThreadOfStations
}

/// Service provides wrapper over the autogenerated OpenAPI client for the "getRouteStations" method
final class ThreadOfStationsService: ThreadOfStationsServiceProtocol {
    private let client: Client
    private let apikey: String
    
    init(client: Client, apikey: String) {
        self.client = client
        self.apikey = apikey
    }
    
    /// Retrieves a thread of station by given thread ID along with info about thread and stops along the routes
    /// - Parameter uid: thread ID in yandex.rasp. Might changes, before each request better to check out actual ID by "routesBetweenStations", "routesFromStation" requests
    /// - Returns: a list of route stations by the specified thread ID with details of the thread and its stops
    func getThreadOfStations(by uid: String) async throws -> ThreadOfStations {
        let response = try await client.getRouteStations(query: .init(
            apikey: apikey,
            uid: uid
        ))
        
        return try response.ok.body.json
    }
}

/// Func for test API call "getRouteStations" method
func testFetchListOfStations() {
    Task {
        do {
            let client = Client(
                serverURL: try Servers.Server1.url(),
                transport: URLSessionTransport()
            )
            
            let service = ThreadOfStationsService(
                client: client,
                apikey: appKeys.yandexRaspAPIKey.rawValue
            )
            
            print("Fetching thread of stations...")
            let response = try await service.getThreadOfStations(
                by: "741A_1_2"
            )
            print("Got response", response)
        } catch {
            print("Error fetching thread of stations:", error)
        }
    }
}
