//
//  CarrierInfoService.swift
//  Schedulo
//
//  Created by Viktor Zavhorodnii on 08/06/2025.
//
 
import OpenAPIRuntime
import OpenAPIURLSession

typealias CarrierInfo = Components.Schemas.CarrierResponse

protocol CarrierInfoServiceProtocol {
    func getCarrierInfo(by: String) async throws -> CarrierInfo
}

/// /// Service provides wrapper over the autogenerated OpenAPI client for the "getCarrierInfo" method
final class CarrierInfoService: CarrierInfoServiceProtocol {
    private let client: Client
    private let apikey: String
    
    init(client: Client, apikey: String) {
        self.client = client
        self.apikey = apikey
    }
    
    /// Retrieves info about carrier by given carrier code
    /// - Parameter code: carrier code, code might be found from getScheduleBetweenStations, getStationSchedule, getRouteStations methods
    /// - Returns: carrier info
    func getCarrierInfo(by code: String) async throws -> CarrierInfo {
        let response = try await client.getCarrierInfo(query: .init(
            apikey: apikey,
            code: code
        ))
        
        return try response.ok.body.json
    }
}

/// Func for test API call "getCarrierInfo" method
func testFetchCarrierInfo() {
    Task {
        do {
            let client = Client(
                serverURL: try Servers.Server1.url(),
                transport: URLSessionTransport()
            )
            
            let service = CarrierInfoService(
                client: client,
                apikey: appKeys.yandexRaspAPIKey.rawValue
            )
            
            print("Fetching carrier info...")
            let response = try await service.getCarrierInfo(
                by: "680"
            )
            print("Got response", response)
        } catch {
            print("Error fetching carrier info:", error)
        }
    }
}
