//
//  ListOfAvailableStations.swift
//  Schedulo
//
//  Created by Viktor Zavhorodnii on 08/06/2025.
//

import OpenAPIRuntime
import OpenAPIURLSession
import Foundation

typealias AllStations = Components.Schemas.AllStationsResponse

protocol ListOfAvailableStationsServiceProtocol {
    func getListOfAvailableStations() async throws -> AllStations
}

/// /// Service provides wrapper over the autogenerated OpenAPI client for the "getAllStations" method
final class ListOfAvailableStationsService: ListOfAvailableStationsServiceProtocol {
    private let client: Client
    private let apikey: String
    
    init(client: Client, apikey: String) {
        self.client = client
        self.apikey = apikey
    }
    
    /// Retrieves list of station which YandexRasp provides information about
    /// - Returns: decoded info in AllStations format. It is the only method which returns data in html format, so the data must be processed
    func getListOfAvailableStations() async throws -> AllStations {
        let response = try await client.getAllStations(query: .init(
            apikey: apikey
        ))
        
        let responseBody = try response.ok.body.text_html_charset_utf_hyphen_8
        
        let limit = 50 * 1024 * 1024
        let fullData = try await Data(collecting: responseBody, upTo: limit)
        
        let allStations = try JSONDecoder().decode(AllStations.self, from: fullData)
        
        return allStations
    }
}

/// Func for test API call "getAllStations" method
func testFetchAllStations() {
    Task {
        do {
            let client = Client(
                serverURL: try Servers.Server1.url(),
                transport: URLSessionTransport()
            )
            
            let service = ListOfAvailableStationsService(
                client: client,
                apikey: appKeys.yandexRaspAPIKey.rawValue
            )
            
            print("Fetching list of stations...")
            let response = try await service.getListOfAvailableStations()
            print("Got response", response)
        } catch {
            print("Error fetching list of stations:", error)
        }
    }
}
